### ISSUE TITLE
fix vertical alignment

### ISSUE THREAD

**Issue by jleb** [hedayaty/NetSpeed#28] opened 2015-04-12 23:48 UTC
Great extension! My one little nag is a cosmetic issue. It seems like the text in the status bar is not aligned the same way the rest is (see attached screenshot).

![netspeed_crop](https://cloud.githubusercontent.com/assets/1663466/7108193/d2a2b71e-e14c-11e4-8514-f1c0a675ba22.png)

**Comment by terrycloth** [comment] 2017-03-16 08:28
I think this is a duplicate of #24, although this one is written more clearly. The screenshot helps too.

**Comment by terrycloth** [comment] 2017-09-05 22:47
Seems like this was fixed at some point? I measured a screenshot today, with the latest NetSpeed installed from GNOME Software, and the vertical position of the top-bar clock on the NetSpeed indicator match exactly.

**Comment by terrycloth** [comment] 2017-09-05 22:48
Seems like this was fixed at some point? I measured a screenshot today, with the latest NetSpeed installed from GNOME Software, and the vertical position of the top-bar clock on the NetSpeed indicator match exactly.

**Comment by terrycloth** [comment] 2017-09-05 22:49
If we close this, we can close #24 too.

**Comment by granjerox** [comment] 2017-09-15 20:15
I can confirm I have this problem. But is only in conjuntion with DashToPanel
![image](https://user-images.githubusercontent.com/2721558/30501575-45d37a94-9a63-11e7-8748-3a71bea9fcdc.png)

![netspeed-vertical-aligment](https://user-images.githubusercontent.com/2721558/30501524-23a7bdfe-9a63-11e7-94f7-75b64df0347a.png)

**Comment by hedayaty** [comment] 2018-02-05 07:27
Fixed by https://github.com/hedayaty/NetSpeed/pull/29

**Closed by hedayaty** 2018-02-05 07:27 UTC
Labels: not-sure
